### ISSUE TITLE
MMGCN

### ISSUE THREAD

**Issue by Weiyinyin11** [feiyuchen7/IRA#1]
Hello, I saw that you reproduced this paper with the toy dataset provided by the author of MMGCN. Could you please tell me what is the result of using the toy dataset to reproduce it?
Is it convenient for you to leave an email address, and can I ask you some questions?

**Comment by feiyuchen7** [comment]
> Hello, I saw that you reproduced this paper with the toy dataset provided by the author of MMGCN. Could you please tell me what is the result of using the toy dataset to reproduce it? Is it convenient for you to leave an email address, and can I ask you some questions?

Hi,
I did not reproduce MMGCN but only have run the codes.
It's been quite a while so I can't recall the results and implementation details. But it's just a toy dataset so the results don't match with those in the paper.
